import test from 'node:test';
import assert from 'node:assert/strict';
import { spawnSync } from 'node:child_process';
import { fileURLToPath } from 'node:url';
const sdk = process.env.THREADROOM_PI_SDK_ROOT;
test('actual package MAIN registers each owned private producer once while keeping shared tools and honest unsupported-host outcomes', { skip: !sdk && 'Pi peer absent; set THREADROOM_PI_SDK_ROOT', timeout: 30000 }, () => {
  const root = fileURLToPath(new URL('../../../', import.meta.url));
  const fixture = fileURLToPath(new URL('../fixtures/main-wiring-proof.mjs', import.meta.url));
  const result = spawnSync(process.execPath, [fixture, root, sdk], { encoding: 'utf8', timeout: 25000 });
  assert.equal(result.status, 0, result.stderr || result.stdout);
  const proof = JSON.parse(result.stdout);
  assert.equal(proof.rawProducerRegistrationsExactlyOnce, true);
  assert.equal(proof.olderSdkCapabilityBoundary, true);
  assert.equal(proof.stockBlockingOnlyAsks, true);
  assert.equal(proof.stockAsyncPersistence, true);
  assert.equal(proof.stockPromotionIdentity, true);
  assert.equal(proof.stockPromotionNoDuplicate, true);
  assert.equal(proof.stockPromotionCancelPreservesQuestion, true);
  assert.equal(proof.stockAnswerBeforeWaitNoDuplicate, true);
  assert.equal(proof.stockSaveThenAbortRecoversFeedback, true);
  assert.equal(proof.stockOriginalEditorCaret, true);
});
